# Generated by Django 4.1 on 2022-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_ads"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="class_name",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="number_company",
            field=models.CharField(default="+998", max_length=14),
        ),
    ]
