# Generated by Django 4.1 on 2022-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_remove_ads_image2_remove_ads_image3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slugone",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
