# Generated by Django 4.1 on 2022-11-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_category_slugone"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/%y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/%y/%m/%d"
            ),
        ),
    ]
